---
- name: create acme config
  template:
    src: acme-client.conf.j2
    dest: /etc/excision/ssl/acme-client.conf
    owner: root
    group: wheel
    mode: "0644"

- name: create acme certs
  command: excision renew-certs
  register: renew_certs
  failed_when: renew_certs.rc == 1
  changed_when: renew_certs.rc == 0
  when: migration is false

- name: generate dane record
  command: excision gen-dane "{{ mail_subdomain }}" "{{ item.name }}" "{{ item.ssl_key_type|default(ssl_key_type) }}"
  register: __gen_dane
  failed_when: __gen_dane.rc != 0 and __gen_dane.rc != 1
  with_items: "{{ domains }}"
