---
- name: create acme config
  template:
    src: acme-client.conf.j2
    dest: /etc/excision/ssl/acme-client.conf
    owner: root
    group: wheel
    mode: "0644"

- name: create acme certs
  command: excision renew-certs
  register: renew_certs
  failed_when: renew_certs.rc == 1
  changed_when: renew_certs.rc == 0
  when: migration is false
