#!/bin/sh

. /usr/local/lib/excision/helpers/variables

# we do certain small checks to make sure that
# the GPG WKS hierarchy is correct

# first lets make sure the top level 
# directory exists and is correctly owned 
#  (NOTE: 2750)
mkdir -p "$wks_home"
chown excision:excision "$wks_home"
chmod 2750 "$wks_home"

# we now regenerate all submission addresses for each
# domain (they are needed to allow authenticated users
#          to send mails to)

# first empty that file
: > "$spam_home/submission-address"
# add each domains wks-submission address
while read -r domain; do
	mkdir -p "$wks_web_home/$domain"
	ln -sfh "$wks_web_home/$domain" "$wks_home/$domain"
	echo "wks@$domain" >> "$spam_home/submission-address"
done < /etc/mail/vdomains

# make sure the web key directory exists as well
mkdir -p "$wks_web_home"
chown -R excision:excision "$wks_web_home"

# now do the bulk of the init using the excision account
su -s /bin/sh excision -c "sh /var/excision-home/excision-wks-init"
