#!/bin/sh

# Checks the consistency of user database and password database

. /usr/local/lib/excision/helpers/variables

# <virtuals> is for inbound
virtuals="$user_home/virtual"
# <revirt> is for outbound
revirt="$user_home/revirt"
allowed="$user_home/spamd.alloweddomains"
bak="bak"

if [ -e "$virtuals" ]; then
	mv "$virtuals" "$virtuals.$bak"
fi
if [ -e "$revirt" ]; then
	mv "$revirt" "$revirt.$bak"
fi
if [ -e "$allowed" ]; then
	mv "$allowed" "$allowed.$bak"
fi

touch "$virtuals" "$revirt" "$allowed"

while read -r domain; do
	printf '@%s\n' "$domain" >> "$allowed"
done < /etc/mail/vdomains

for user_file in "$user_home/user-data/"*; do
	username=$( basename "$user_file" )
	printf "\n%s\t\t\t\texcision" "$username" >> "$virtuals"
	printf "\n%s\t\t\t\t%s" "$username" "$username" >> "$revirt"
	while IFS= read -r alias; do
		printf "\n%s\t\t\t\t%s" "$alias" "$username" >> "$virtuals"
		printf ",%s" "$alias" >> $revirt
	done < "$user_home/user-data/$username"
	printf "\n" >> "$revirt"
done

install -m 640 -o root -g _smtpd "$virtuals" /etc/mail/virtual
install -m 640 -o root -g _smtpd "$revirt" /etc/mail/revirt
install -m 640 -o root -g _smtpd "$allowed" /etc/mail/spamd.alloweddomains
install -m 440 -o _smtpd -g _dovecot "$user_home/passwd" /etc/mail/passwd

# Reload information for services
#supposedly dovecot automatically reloads the changes
#but lets not trust anything
rcctl reload dovecot
smtpctl update table passwd
smtpctl update table virtuals
smtpctl update table revirt 
