#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf %s\\n "excision can only be run by root"
	exit 1
fi

HELP=$(cat <<-END
usage:  excision add-alias [alias@domainA.tldA] [user@domainB.tldB]
        excision add-user [user@domain.tld]
        excision change-passwd [user@domain.tld]
        excision daily-report
        excision ensure-dkim
        excision ensure-gpg
        excision ensure-zone [domain.tld]
        excision fix-perms
        excision gen-virtual
        excision gen-dane [mailname domain keytype]
        excision renew-certs
        excision show-stats
        excision userdb-check
        excision whitelist-bigmailer [domain.tld]
        excision whitelist-friend [IP]
END
)

if [ $# -lt 1 ]; then
	printf %s\\n "${HELP}"
	exit 2
fi

command="$1"
shift

script_home="/usr/local/lib/excision"

if [ -f "${script_home}/${command}" ] && [ -x "${script_home}/${command}" ]; then
	"${script_home}/${command}" "${@}"
else
	printf %s\\n "${HELP}"
	exit 3
fi
