---
- name: make excision group
  group:
    name: excision
    gid: 2000

- name: make excision user
  user:
    name: excision
    comment: Excision Mail executor
    uid: 2000
    group: excision
    groups: ""
    login_class: daemon
    shell: /sbin/nologin
    home: /var/excision

- name: disable logins for excision user
  file:
    state: absent
    path: /var/excision/.ssh/
