---
- name: check if excision group exists
  getent:
    database: group
    key: excision
  register: excision_group
  ignore_errors: true

- name: make excision group
  group:
    name: excision
    gid: 2000
  when: excision_group.failed or excision_group is not defined

- name: check if excision user exists
  getent:
    database: passwd
    key: excision
  register: excision_user
  ignore_errors: true

- name: make excision user
  user:
    name: excision
    comment: Excision Mail executor
    uid: 2000
    group: excision
    groups: ""
    login_class: daemon
    shell: /sbin/nologin
    home: /var/excision
  when: excision_user.failed or excision_user is not defined

- name: disable logins for excision user
  file:
    state: absent
    path: /var/excision/.ssh/
