---
- name: create web root directory
  file:
    path: "{{ base_web_config_dirs.root.path }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ base_web_config_dirs.root.perm }}"
    modification_time: preserve
    access_time: preserve

- name: create web subdirectories
  file:
    path: "{{ base_web_config_dirs.root.path }}/{{ item.name }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.perm }}"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ base_web_config_dirs.subdir }}"

- name: generate mta-sts.txt file
  template:
    src: mta-sts.txt.j2
    dest: "{{ base_web_config_dirs.root.path }}/mta-sts/mta-sts.txt"
    owner: root
    group: wheel
    mode: '0644'

# https://wiki.mozilla.org/Thunderbird:Autoconfiguration#Implementation
- name: generate mozilla config files
  template:
    src: config-v1.1.xml.j2
    dest: "{{ base_web_config_dirs.root.path }}/mail/config-v1.1.xml"
    owner: root
    group: wheel
    mode: '0644'

# https://github.com/gronke/email-autodiscover/blob/master/mail/autodiscover.xml
# https://docs.microsoft.com/en-us/previous-versions/office/office-2010/cc511507(v=office.14)?redirectedfrom=MSDN#Anchor_3
- name: generate autodiscover config files
  template:
    src: Autodiscover.xml.j2
    dest: "{{ base_web_config_dirs.root.path }}/Autodiscover/Autodiscover.xml"
    owner: root
    group: wheel
    mode: '0644'
